#FILMS
drama = ["The Misfits (1961)", "2046 (2004)", "My Own Private Idaho (1991)", "The Virgin Spring (1960)", "Pather Panchali (1955)", "Beanpole (2019)", "Black Bear (2020)", "Elisa & Marcela (2019)", "Mishima - A Life in Four Chapters (1985)", "Sunset Boulevard (1950)", "Scenes from a Marriage (1974)", "Frida (2002)", "Tropical Malady (2004)", "Double Indemnity (1944)", "Woman in the Dunes (1964)", "Ikiru (1952)", "Wolfwalkers (2020)","Pieces of a Woman (2020)", "The Nest (2020)", "Citizen Kane (1941)", "Malina (1991)", "Cleo from 5 to 7 (1962)", "Tokyo Story (1953)", "The Silence (1963)", "Damnation (1988)", "8 and a Half (1963)", "Certain Women (2016)", "Capernaum (2018)", "The Kings of Summer (2013)", "Youth (2015)", "Mysterious Skin (2004)", "Das Boot (1981)", "Gummo (1997)", "Amy (2015)", "The Souvenir (2015)", "The Art of Self-Defense (2019)", "Fallen Angels (1995)", "A Brighter Summer Day (1991)", "A Woman Under the Influence (1974)", "Ida (2103)", "Jeanne Dielman (1975)", "The Blind Side (2009)", "Fences (2016)", "At Eternity's Gate (2018)", "Three Colors - Trilogy (1994)", "Wonder (2017)", "The Danish Girl (2015)", "Girl, interrupted (1999)", "The Artist (2011)", "Cinema Paradiso (1988)", "The Hunt (2012)", "Wind River (2011)", "Paris, Texas (1984)", "A Beautiful Mind (2001)", "Honey Boy (2019)", "The Post (2017)", "Hunt for the Wilderpeople (2016)", "Moon (2009)", "Argo (2012)", "The King's Speech (2010)", "Inherent Vice (2014)", "In Bruges (2008)", "The Curious Case of Benjamin Button (2008)", "The Tree of Life (2011)", "Rosemary's Baby (1968)", "A Ghost Story (2017)", "The Great Gatsby (2013)", "You Were Never Really Here (2017)", "Dead Poet's Society (1989)", "Silver Linings Playbook (2012)", "Inside Llewyn Davis (2013)", "Little Miss Sunshine (2006)", "Spotlight (2015)", "Manchester by the Sea (2016)", "Boyhood (2014)", "Schindler's List (1993)", "Phantom Thread (2017)", "Room (2015)", "The Florida Project (2017)", "Roma (2018)", "The Father (2020)", "High and Low (1963)", "Central Station (1998)", "Persona (1966)", "Ran (1985)", "The Passion of Joan Arc (1928)", "Santantango (1994)", "Andrei Rublev (1966)", "Close-Up (1996)", "Autumn Sonata (1978)", "Fanny & Alexander (1982)", "Eternity and a Day (1998)", "The Apartment (1960)", "Le Trou (1960)", "The Red Shoes (1948)", "Macario (1960)", "Mirror (1975)", "Ordet (1955)", "I am Cuba (1964)", "Barry Lyndon (1975)", "Nights of Cabiria (1957)", "The Battle of Algiers (1966)", "Landscape in the Midst (1988)", "The Pianist (2002)", "The Second Mother (2015)", "An Elephant Sitting Still (2018)"]

romance = ["The Woman Next Door (1981)", "A Streetcar Named Desire (1951)", "Rebel Without a Cause (1955)", "Punch-Drunk Love (2002)", "Last Tango in Paris (1972)", "Kiss Me Deadly (1955)", "Hiroshima Mon Amour (1959)", "How to Lose a Guy in 10 Days (2003)", "Matchpoint (2005)", "God's Own Country (2017)", "Revolutionary Road (2008)", "Me Before You (2016)", "Pretty Woman (1990)", "Romeo + Juliet (1996)", "Love, Actually (2003)", "It's a Wonderful Life (1946)", "Before Trilogy (1995)", "Midnight in Paris (2011)", "Blue Velvet (1986)", "Amelie (2001)", "A Star is Born (2018)", "The Young Girls of Rochefort (1961)", "Wings of Desire (1987)", "La Notte (1961)", "Nostalgia (1983)", "Happy Together (1997)", "In a Lonely Place (1980)", "The Mother and the Whore (1973)", "Amour (2012)", "The Lovers on the Bridge (1991)", "The Green Ray (1986)", "My Night at Maud's (1969)", "Roman Holiday (1953)", "Trouble in Paradise (1932)", "Orpheus (1950)", "Harold and Maude (1971)", "And Then We Danced (2019)", "Certified Copy (2010)", "Breaking the Waves (1996)", "Annie Hall (1977)", "Syndromes and a Century (2006)", "L'Eclisse (1962)", "Volver (2006)", "Lovers Rock (2020)", "Belle de Jour (1962)", "Cabaret (1972)", "Atonement (2007)", "If Beale Street Could Talk (2018)", "Victoria (2015)", "Paterson (2016)", "A Nos Amours (1985)", "Lola (1961)", "Once (2007)", "Anomalisa (2015)", "West Side Story (2021)", "The Piano (1993)", "November (2017)", "Loves of a Blonde (1965)", "Summer with Monika (1953)", "Moonstruck (1987)", "Breakfast at Tiffany's (1961)", "Corpse Bride (2005)", "Martin Eden (2019)", "Emma (2020)", "Juno (2007)", "Queen & Slim (2019)", "Disobedience (2017)", "Never Let Me Go (2010)", "The World To Come (2020)", "You've Got Mail (1998)", "Pretty in Pink (1986)", "Julie & Julia (2009)", "Cafe Society (2016)", "The Spectacular Now (2013)", "Children of Paradise (1945)", "The Weeping Meadow (2004)", "Day of Wrath (1943)", "Kiss of the Rabbit God (2019)", "Oasis (2002)", "Us and Them (2018)", "Badlands (1973)", "L'Atalante (1934)", "What Happened Was... (1994)", "Maurice (1987)", "Buffalo '66 (1998)", "A Married Couple (1969)", "Rendezvous (1976)", "Drugstore Romance (1979)", "Stolen Kisses (1968)", "An Unmarried Woman (1978)", "Millenium Mambo (2001)", "Dogfight (1991)", "Little England (2013)", "Metropolitan (1992)", "Blue Valentine (2010)", "The Last Days of Disco (1998)", "Heartstone (2016)", "Pauline at the Beach (1983)", "Friday Night (2002)", "Antoine and Collette (1962)", "Frantz (2016)", "A Swedish Love Story (1970)", "The Panic in Needle Park (1971)", "On Body and Soul (2017)"]

asa = ["Ben-Hur (1959)", "Jurassic Park (1993)", "The Great Escape (1963)", "A.I Artificial Intelligence (2001)", "The Terminator (1984)", "Aliens (1986)", "The Deer Hunter (1978)", "North by Northwest (1959)", "Metropolis (1927)", "Inferno (2016)", "Tenet (2020)", "The Iron Giant (1999)", "All Quiet on the Western Front (1930)", "Rififi (1955)", "Brazil (1985)", "Lawrence of Arabia (1962)", "Once Upon a Time in the West (1968)", "Lord of War (2005)", "The Devil's Advocate (1997)", "Vanilla Sky (2001)", "Malcolm X (1992)", "Black Hawk Down (2001)", "The Accountant (2016)", "Chappie (2015)", "Kiss Kiss Bang Bang (2005)", "Quantam of Solace (2008)", "The Third Man (1949)", "Cloud Atlas (2012)", "L.A Confidential (1997)", "Fury (2014)", "Paths of Glory (1957)", "Snatch (2000)", "Les Miserables (2012)", "Stalker (1979)", "Akira (1988)", "Heat (1995)", "The Usual Suspects (1995)", "Hell or High Water (2016)", "Seven Samurai (1954)", "Watchmen (2009)", "The Girl with the Dragon Tattoo (2011)", "The Good, The Bad and The Ugly (1966)", "Ghostbusters (1984)", "The Nightmare Before Christmas (1993)", "Scarface (1983)", "Full Metal Jacket (1987)", "E.T (1982)", "Ad Astra (2019)", "Die Hard (1988)", "Raiders of the Lost Ark (1981)", "Apocalypse Now (1979)", "Pan's Labyrinth (2006)", "The Big Lebowski (1998)", "Wall-E (2008)", "The Hateful Eight (2015)", "Reservoir Dogs (1992)", "Leon (1994)", "The Blues Brothers (1980)", "Skyfall (2012)", "Tokyo Drifter (1966)", "Run Lola Run (1998)", "Mandy (2018)", "Revenge (2017)", "Hanna (2011)", "Top Gun (1986)", "Allied (2016)", "Public Enemies (2009)", "Constantine (2005)", "The Hunt (2020)", "Hard-Boiled (1992)", "Howl's Moving Castle (2004)", "The Wages of Fear (1953)", "A Touch of Zen (1971)", "The Wild Bunch (1969)", "Captain Fantastic (2016)", "Into the Wild (2007)", "True Grit (2010)", "The Fifth Element (1997)", "Hugo (2011)", "127 Hours (2010)", "The Fountain (2006)", "The Lost City of Z (2016)", "The Polar Express (2004)", "Alice in Wonderland (2010)", "The Jungle Book (2016)", "Arabian Nights (1974)", "La Jetee (1962)", "The Fly (1986)", "Videodrome (1983)", "12 Monkeys (1995)", "Melancholia (2011)", "28 Days Later (2002)", "Contagion (2011)", "Finch (2021)", "The Platform (2019)", "Third Kind (2018)", "The Circle (2017)", "Colossal (2016)"]

horror = ["Let the Right One In (2008)", "4 Months, 3 Weeks and 2 Days (2007)", "Possession (1981)", "Possessor (2020)", "House (1977)", "Carrie (1976)", "Drag Me To Hell (2009)", "Funny Games (1997)", "A Cure for Wellness (2016)", "Dawn of the Dead (1978)", "The Texas Chainsaw Massacre (1974)", "Train to Busan (2016)", "Bird Box (2018)", "The Thing (1982)", "Jaws (1975)", "The Witch (2015)", "Alien (1979)", "The Innocents (1961)", "The Cabinet of Caligari (1920)", "Scream (1996)", "Night of the Living Dead (1968)", "Peeping Tom (1960)", "Hour of the Wolf (1968)", "Halloween (1978)", "Deep Red (1975)", "Nosferatu (1922)", "Repulsion (1965)", "The Tenant (1976)", "Vampyr (1932)", "A Nightmare on Elm Street (1984)", "Don't Look Now (1973)", "Inland Empire (2006)", "X (2022)", "Climax (2018)", "Candyman (1992)", "Green Room (2015)", "Funny Games (2007)", "Stoker (2013)", "Ready or Not (2019)", "Mother! (2017)", "His House (2020)", "The Invisible Man (2020)", "The Babadook (2014)", "Inferno (1980)", "Antichrist (2009)", "The Blackcoat's Daughter (2015)", "The Invitation (2015)", "Don't Breathe (2016)", "Unsane (2018)", "It Comes at Night (2017)", "The Neon Demon (2016)", "Drag Me To Hell (2009)", "Greta (2018)", "In The Tall Grass (2019)"]

comedy = ["Airplane! (1980)", "Safety Last! (1923)", "Shrek (2001)", "Yes Man (2008)", "Everybody Wants Some! (2016)", "13 Going on 30 (2004)", "Matilda (1996)", "The Room (2003)", "Elf (2003)", "When Harry Met Sally (1989)", "Monty Python and The Holy Grail (1975)", "Groundhog Day (1993)", "Dr. Strangelove (1964)", "500 Days of Summer (2009)", "The Disaster Artist (2017)", "Hot Fuzz (2007)", "Toy Story (1995)", "Ferris Beuller's Day Off (1985)", "Moana (2016)", "Popstar - Never Stop Never Stopping (2016)", "The Little Hours (2017)", "The House (2017)", "Welcome to Me (2014)", "Carnage (2011)", "Dom Hemingway (2013)", "Get Him to The Greek (2010)", "Death at A Funeral (2007)", "Dolemite Is My Name (2019)", "Ghost World (2001)", "Get Duked! (2019)", "Buffaloed! (2019)", "Young Adult (2011)", "Ace Ventura (1994)", "Dinner for Schmucks (2010)"]

tms = ["Casino (1995)", "Trainspotting (1996)", "The Ascent (1977)", "The Butterfly Effect (2004)", "Magnolia (1999)", "The Sixth Sense (1999)", "V for Vendetta (2005)", "Finding Nemo (2003)", "Eyes Wide Shut (1999)", "Nocturnal Animals (2016)", "One Flew Over the Cuckoo's Nest (1975)", "Vertigo (1958)", "12 Angry Men (1957)", "Requiem for a Dream (2000)", "Prisoners (2013)", "Split (2016)", "Donnie Darko (2001)", "Zodiac (2007)", "Memento (2000)", "Black Swan (2010)", "Le Samourai (1967)", "Dogville (2003)", "Pierrot Le Fou (1965)", "Lost Highway (1997)", "Victoria (2015)", "We Need To Talk About Kevin (2011)", "Irreversible (2002)", "Collateral (2004)", "The Killing of a Sacred Deer (2017)", "Searching (2018)", "The Nightingale (2018)", "Enemy (2013)", "The Novice (2021)", "Crash (1996)", "The Double (2013)", "Natural Born Killers (1994)", "Kill Your Darlings (2013)", "The Card Counter (2021)", "Personal Shopper (2016)", "Side Effects (2013)", "High Life (2018)", "Rear Window (1954)", "Sherlock Jr. (1924)", "Chinatown (1974)", "3 Women (1977)", "L'Avventura (1960)", "Cache (2005)", "Theorem (1968)", "Picnic At Hanging Rock (1975)", "The Kid Detective (2020)"]

#SHOWS
aatv = ["The Umbrella Academy"]

scifi = ["Love, Death & Robots", "The Expanse", "Dark", "Devs"]

dramatv = ["My So-Called Life", "Freaks and Geeks", "Band of Brothers", "Deutschland", "Downton Abbey", "Downton Abbey", "Boardwalk Empire", "The Deuce", "Big Little Lies", "Babylon Berlin", "Sharp Objects", "Better Call Saul", "Unbelievable", "Twin Peaks", "Rectify", "Six Feet Under", "Broadchurch", "Maid"]

comedytv = ["Documentary Now!", "Key and Peele", "Veep"]

#ALBUMS
hiphop = ["Sometimes I Might Be Introvert by Little Simz", "Circles by Mac Miller", "Call Me If You Get Lost by Tyler the Creator", "IGOR by Tyler the Creator", "Some Rap Songs by Earl Sweatshirt", "Common Sense by J-Hus", "Gang Signs & Prayer by Stormzy", "At Long Last by ASAP Rocky", "Section .80 by Kendrick Lamar", "Acid Rap by Chance the Rapper", "My Beautiful Dark Twisted Fantasy by Kanye West", "Madvilliany by Madvillian", "Mm.. Food by MF DOOM", "The Eminem Show by Eminem", "Quality by Talib Kweli", "The Blueprint by Jay-Z", "Stankonia by OutKast", "The Marshall Mathers LP by Eminem", "Yesterday's Gone by Loyle Carner", "Things Fall Apart by The Roots", "The Miseducation of Lauryn Hill by Lauryn Hill", "The Infamous by Mobb Deep", "All Eyez On Me by 2Pac", "Ready To Die by The Notorious B.I.G", "Enter the Wu-Tang Clan by Wu-Tang Clan", "Midnight Marauders by A Tribe Called Quest", "Doggystyle by Snoop Dogg", "The Chronic by Dr. Dre", "De La Soul Is Dead by De La Soul", "It Takes A Nation Of Millions To Stop Us by Public Enemy", "AmeriKKKas Most Wanted by Ice Cube", "Black On Both Side by Mos Def", "Paid in Full by Eric B. & Rakim", "i am > i was by 21 Savage", "Redemption by Jay Rock", "DiCaprio 2 by JID", "Beerbongs & Bentleys by Post Malone"]

indiealt = ["Daddy's Home by St. Vincent", "Valentine by Snail Mail", "Punisher by Phoebe Bridgers", "Set My Heart On Fire by Perfume Genius", "Sawayama by Rina Sawayama", "High As Hope by Florence + The Machine", "No Shape by Perfume Genius", "The Ooz by King Krule", "Carrie & Lowell by Sufjan Stevens", "Too Bright by Perfume Genius", "Hurry Up, We're Dreaming by M83", "Sea Chance by Beck", "In The Aeroplane Over The Sea by Neutral Milk Hotel", "Beneath The Skin by Of Monsters and Men", "Demon Dayz by Gorillaz", "Be The Cowboy by Mitski", "Soft Sounds From Another Planet by Japanese Breakfast", "Contra by Vampire Weekend", "Fetch The Bolt Cutters by Fiona Apple"]

randb = ["Heaux Tales by Jazmine Sullivan", "Still Over It by Summer Walker", "Magdalene by FKA Twigs", "Isolation by Kali Uchis", "ctrl by SZA", "Malibu by Anderson Paak.", "Beauty Behind The Madness by The Weeknd", "LP1 by FKA Twigs", "Caprisongs by FKA Twigs", "Channel Orange by Frank Ocean", "Mama's Gun by Erykah Badu", "Lost and Found by Jorja Smith", "What's the 411? by Mary J. Blige", "What's Going On by Marvin Gaye", "Ballads 1 by Joji", "A Seat At At The Table by Solange", "Freudian by Daniel Ceasar", "Ivory by Omar Apollo", "Tyron by Slowthai"]

pop = ["After Hours by The Weeknd", "Dawn FM by The Weeknd", "Immunity by Clairo", "El Mal Querer by Rosalia", "The Rise and Fall of Ziggy Stardust and the Spiders from Mars by David Bowie", "Currents by Tame Impala", "Melodrama by Lorde", "Golden Hour by Kacey Musgraves", "A Brief Enquiry Into Online Relationships by The 1975", "Pop 2 by Charli XCX", "Days Are Gone by HAIM", "25 by Adele", "Anti by Rihanna", "Sour by Olivia Rodrigo", "Take Care by Drake", "Pure Heroine by Lorde", "Night Time, My Time by Sky Ferreira", "Krystal by Matt Maltese"]

#BOOKS
fiction = ["Candide by Voltaire", "The Complete Works of William Shakespeare", "The Awakening by Kate Chopin", "Siddharta by Herman Hesse", "The Goldfinch by Donna Tartt", "Nostromo by Joseph Conrad", "Little Women by Louisa May Alcott", "War and Peace by Leo Tolstoy", "Tropic of Cancer by Henry Miller", "The Trial by Franz Kafka", "To Kill A Mockingbird by Lee Harper", "Tess of the D'Ubervilles by Thomas Hardy", "Pride and Prejudice by Jane Austen", "The Old Man and The Sea by Ernest Hemingway", "Of Mice and Men by John Steinbeck", "Never Let Me Go by Kazuo Ishiguro", "Mrs. Dalloway by Virginia Woolf", "Ulysses by James Joyce", "Middlemarch by George Eliot", "Love in the Time of Cholera by Gabriel Garcia Marquez", "The Kite Runner by Khalid Hosseini", "The Great Gatsby by F. Scott Fitzgerald", "Great Expectations by Charles Dickens", "The Grapes of Wrath by John Steinbeck", "Done Quixote by Miguel Cervantes", "City of Thieves by David Benioff", "The Chrysalid by John Wyndham", "The Catcher in The Rye by J.D Salinger", "Catch-22 by Joseph Heller", "The Brothers Karamazov by Fyodor Dostoevsky", "The Giver by Lois Lowry", "Someone Knows My Name by Lawrence Hill", "The Bell Jar by Sylvia Plath", "Fahrenheit 451 by Ray Bradbury", "The Alchemist by Paolo Coelho","A Town Like Alice by Nevil Shute", "Lord of The Flies by William Golding", "Jane Eyre by Charlotte Bronte","A Tale of Two Cities by Charles Dickens"]

science = ["Parallel Worlds by Michio Kaku", "Quiet by Susan Cain", "Silent Spring by Rachel Carson", "The Fabric of The Cosmos by Brian Greene", "Guns, Germs and Steel by Jared Diamond", "Astrophysics for People In a Hurry by Neil DeGrasse Tyson", "Origins by Lewis Dartnell", "What If? by Randall Munroe", "Cosmos by Carl Sagan"]

philosophy = ["The Essays by Michel De Montaigne", "The Prince by Nicolo Macchiavelli", "The Art of Strategy by Sun Tzu", "Sophie's World by Jostein Gardner", "The Myth of Sisyphus by Albert Camus", "The Symposium by Plato", "Meditations on First Philosophy by Rene Descartes", "On the Genealogy of Morals by Friedrich Nietzsche", "Selected Writings by Thomas Aquinas", "Three Philosophical Dialogues by Anselm of Canterbury", "The Nicomachean Ethics by Aristotle", "The Philosophical Works of Al-Kindi", "Avicenna on Theology", "The Metaphysics of Healing by Avicenna", "Al-Ghazali's Philosophical Theology by Frank Griffel", "Faith and Reason in Islam by Ibn Rushd", "The Bezels of Wisdom by Ibn Arabi"]

nonfiction = ["Women and Gender in Islam by Leila Ahmed", "Silent Spring by Rachel Carson", "The Autobiography of Malcolm X", "A Short History of Nearly Everything by Bill Bryson", "Night by Ellie Weisel", "The Beauty Myth by Naomi Wolf", "The Diary of a Young Girl by Anne Frank", "Hiroshima by John Hersey", "Bury My Heart at Wounded Knee by Dee Brown", "The Meccan Revelations by Ibn Arabi"]

historicalfiction = ["The Agony and The Ecstasy by Irving Stone", "The English Patient by Michael Ondaatje", "The Scarlet Letter by Nathaniel Hawthorne", "Girl With a Pearl Earring by Tracy Chevalier", "Sarah's Key by Tatiana De Rosnay", "The Three Musketeers by Alexandre Dumas", "The Nightingale by Kristin Hannah"]

contemporary = ["We Are The Ants by Shaun David Hutchinson", "The Perks of Being a Wallflower by Stephen Chbosky", "Lie With Me by Philippe Besson", "Call Me By Your Name by Andre Aciman", "Maurice by E.M Forster", "Giovanni's Room by James Bladwin", "A Little Life by Hnaya Yanagihara", "The Secret History by Donna Tartt"]

#GAMES

pc = ["Portal 2", "The Outer Wilds", "Mass Effect Trilogy", "Yakuza 0", "Skyrim", "SOMA", "Firewatch", "Bioshock", "Batman Trilogy", "What Remains of Edith Finch", "Nier Automata", "L.A Noire", "Star Wars - Knights of The Old Republic", "Sleeping Dogs", "Dishonored", "Deus Ex Revolution", "The Talos Principle"]

ps4 = ["Fallout 4", "Bloodborne", "Control", "Uncharted 4", "Metal Gear Solid 5", "Assassin's Creed Odyssey", "Days Gone", "Ghost of Tsushima", "The Witcher", "For Honor", "Rise of The Tomb Raider", "Star Wars Jedi Fallen Order"]
